# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac17c490dbf104133c9086d93d0e0993f14e30c02bf45f281312ce3c90245a327c6c2d69cffc09d3eba83d00c9fb8ba51ac077d1e4da98e9dff8b05763f2e5fa

test:
  secret_key_base: ee570a0492c35ff5ec4868ac8f8f8abf54b33ac9cb0e19b2606595035abcf0befcf4b440b7f8f324ccfc2a3288e510fa9ad9d4ae826850b20bdc06445173a5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
